---
networks:
  vpn_net:
    driver: bridge
    attachable: true
  infra_net:
    driver: bridge
    attachable: true
  media_net:
    driver: bridge
    attachable: true

services:
  network-only:
    image: tianon/test:true-oci
    restart: no
    networks:
      - vpn_net
      - infra_net
      - media_net
