---
networks:
  vpn-net:
    driver: overlay
    attachable: true
  infra-net:
    driver: overlay
    attachable: true
  media-net:
    driver: overlay
    attachable: true

services:
  network-only:
    image: tianon/test:true-oci
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    networks:
      - vpn-net
      - infra-net
      - media-net
