---
networks:
  vpn_net:
    driver: overlay
    attachable: true
  infra_net:
    driver: overlay
    attachable: true
  media_net:
    driver: overlay
    attachable: true

services:
  network-only:
    image: tianon/test:true-oci
    deploy:
      replicas: 0
      restart_policy:
        condition: none
    networks:
      - vpn_net
      - infra_net
      - media_net
