---
networks:
  networks_infra_net:
    external: true

services:
  npm:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    deploy:
      replicas: 1
    ports:
      - '8080:80'
      - '8181:81'
      - '443:443'
    volumes:
      - /mnt/HomeLab/Nginx-Proxy-Manager/data:/data
      - /mnt/HomeLab/Nginx-Proxy-Manager/letsencrypt:/etc/letsencrypt
    networks:
      - networks_infra_net

