---
services:
  app:
    image: 'docker.io/jc21/nginx-proxy-manager:latest'
    deploy:
      replicas: 1
    ports:
      - '8081:80'
      - '8181:81'
      - '8443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - networks_infra-net